In [1]:
## Importar librería

import pandas as pd
import warnings
from sklearn.preprocessing import StandardScaler
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [2]:
## Cargar datos 

data = pd.read_csv('../data/processed/data_eda.csv').sample(frac=0.5)
data.head()

,channel_name,category,Sub-category,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score,issue_reported_year,...,issue_reported_day,issue_reported_hour,issue_responded_year,issue_responded_month,issue_responded_day,issue_responded_hour,survey_response_year,survey_response_month,survey_response_day,survey_response_hour
10881,1,10,40,1038,20,0,2,2,5,2023,...,18,23,2023,8,19,5,2023,8,19,0
10671,1,10,40,502,17,0,3,4,4,2023,...,8,10,2023,8,8,10,2023,8,8,0
13439,2,10,20,1103,5,5,4,1,5,2023,...,21,17,2023,8,21,17,2023,8,21,0
68998,1,5,17,1165,11,3,3,2,5,2023,...,19,13,2023,8,19,13,2023,8,19,0
42678,1,10,39,1233,36,2,0,2,5,2023,...,7,10,2023,8,7,10,2023,8,7,0

In [3]:
X = data.drop('CSAT Score',axis=1)
y = data['CSAT Score']

In [4]:
y.isnull().sum()

0

In [5]:
## Normalización
scaler = StandardScaler()
df_scaler = scaler.fit_transform(X)
data_scaler_X = pd.DataFrame(df_scaler, columns=X.columns)
data_scaler_X ['CSAT Score']=y.values

In [6]:
data_scaler_X.to_csv('../data/processed/data_normalized.csv', index=False)